allowBuilds:
  '@parcel/watcher': false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@effect/ai-typesafe@4.0.0-rc.116'
  - effect@4.0.0-rc.116
  - '@effect/platform-node-shared@4.0.0-rc.116'
  - '@effect/platform-node@4.0.0-rc.116'
