import { type Company } from "./Company.ts";

/** Picking one fills the box and, when it says who is watching, sets the audience pill with it. */
export type Suggestion = { readonly said: string; readonly company: Company | null };

export const SUGGESTIONS: readonly Suggestion[] = [
  // just me
  { said: "The saddest film there is, for a lonely night.", company: "solo" },
  { said: "I got my heart broken. I want a film that helps it heal.", company: "solo" },
  { said: "Long day, home alone. I just want to switch off.", company: "solo" },
  { said: "Rough week. I need to feel something, on my own.", company: "solo" },
  { said: "Can't sleep, nobody's up. Scare me.", company: "solo" },
  { said: "Hungover and alone. Nothing that asks anything of me.", company: "solo" },
  { said: "I want to cry properly, and there's no one here to see.", company: "solo" },
  { said: "Home sick in bed all day by myself.", company: "solo" },
  { said: "Wired from work, flat's empty. Something to come down from it.", company: "solo" },
  { said: "Just got dumped. Something for one.", company: "solo" },
  { said: "Up at 3am again, just me. Something slow and quiet.", company: "solo" },
  { said: "Snowed in on my own and the wifi still works.", company: "solo" },
  { said: "A quiet Sunday alone. Something beautiful I can just stare at.", company: "solo" },
  { said: "Nobody to argue with tonight, so something slow and strange.", company: "solo" },
  { said: "One long film and my full attention, no one else around.", company: "solo" },
  { said: "A series I can fall into for a week on my own.", company: "solo" },
  { said: "Too tired for subtitles and too alone for anything sad.", company: "solo" },
  { said: "My own company and a proper mystery I can try to solve.", company: "solo" },
  { said: "Feeling brave with no one watching. Show me something heavy.", company: "solo" },
  { said: "A Korean thriller for a night in by myself.", company: "solo" },
  { said: "An anime series I can binge alone this weekend.", company: "solo" },
  { said: "A Thai horror film, lights off, just me.", company: "solo" },
  { said: "Something French I can read subtitles for in peace.", company: "solo" },
  { said: "A comfort rewatch for one. Nothing new tonight.", company: "solo" },
  { said: "Under ninety minutes, then bed. It's only me.", company: "solo" },
  // the two of us
  { said: "A Japanese anime for the two of us.", company: "couple" },
  { said: "Date night. Something warm and a little romantic.", company: "couple" },
  { said: "First date. Nothing too intense.", company: "couple" },
  { said: "Anniversary tonight. Something romantic.", company: "couple" },
  { said: "We always argue about what to watch. Give us the highest rated thing.", company: "couple" },
  { said: "We've got wine and no plans.", company: "couple" },
  { said: "Something light to put on while we cook together.", company: "couple" },
  { said: "Watching together on a video call. Something warm and easy.", company: "couple" },
  { said: "A film we can pause and talk through.", company: "couple" },
  { said: "A K-drama my partner will get hooked on with me.", company: "couple" },
  { said: "A Thai romance for the two of us.", company: "couple" },
  { said: "Something properly scary for the two of us.", company: "couple" },
  { said: "A musical the two of us will both survive.", company: "couple" },
  { said: "A slow, gorgeous film for a night in with my wife.", company: "couple" },
  { said: "Our first weekend living together. Something warm.", company: "couple" },
  { said: "A love story that isn't sentimental, for a couple who've heard them all.", company: "couple" },
  { said: "We just finished our series. Give us the highest rated one.", company: "couple" },
  { said: "A Studio Ghibli film for a quiet evening together.", company: "couple" },
  { said: "Something Korean for the two of us, subtitles fine.", company: "couple" },
  { said: "A heist we can both try to work out.", company: "couple" },
  // friends
  { said: "Friends are over. Nothing too serious.", company: "friends" },
  { said: "Big group, everyone's talking. Keep it light.", company: "friends" },
  { said: "Pizza with the gang. Something loud and stupid.", company: "friends" },
  { said: "Something we can shout at together.", company: "friends" },
  { said: "Make us laugh until it hurts. There are six of us.", company: "friends" },
  { said: "A horror film for a room full of friends.", company: "friends" },
  { said: "Zombies, and a group who'll cheer.", company: "friends" },
  { said: "Superheroes for a Friday night with the lads.", company: "friends" },
  { said: "A heist for a group who love being clever.", company: "friends" },
  { said: "Everyone's seen everything. Find us something we haven't.", company: "friends" },
  { said: "A film night that should feel like an event.", company: "friends" },
  { said: "A martial arts film from Hong Kong for the boys.", company: "friends" },
  { said: "Something Thai and funny for a group.", company: "friends" },
  { said: "A competition show we can bet on together.", company: "friends" },
  { said: "A disaster film where the effects hold up, for a crowd.", company: "friends" },
  { said: "Girls' night. Something we'll all cry at.", company: "friends" },
  { said: "A sports film for a group who just lost the match.", company: "friends" },
  { said: "Aliens arriving, and a room full of people to enjoy it.", company: "friends" },
  { said: "A cult classic from the eighties for friends who've never seen it.", company: "friends" },
  { said: "Cars, and a lot of them, for a loud room.", company: "friends" },
  // family
  { said: "A food documentary for family dinner.", company: "family" },
  { said: "Christmas, everyone's here.", company: "family" },
  { said: "My parents are visiting. Something they'd enjoy.", company: "family" },
  { said: "Something my dad would stay awake for: fast, loud and funny.", company: "family" },
  { said: "Something the whole family will sit through.", company: "family" },
  { said: "Teenagers on the sofa. Something they won't call boring.", company: "family" },
  { said: "Three generations in one room.", company: "family" },
  { said: "Grandma picks, and she likes the old ones.", company: "family" },
  { said: "A nature documentary for a family evening.", company: "family" },
  { said: "Sunday dinner with my family. Something gentle.", company: "family" },
  { said: "A classic my mum keeps saying we should watch together.", company: "family" },
  { said: "A Thai film my parents would recognise.", company: "family" },
  { said: "Something funny the whole family can laugh at.", company: "family" },
  { said: "A big adventure for a family movie night.", company: "family" },
  { said: "A true story that will get the family talking.", company: "family" },
  { said: "My in-laws are staying. Nothing awkward.", company: "family" },
  { said: "A musical for a house full of relatives.", company: "family" },
  { said: "A series the family can watch an episode of every night.", company: "family" },
  // kids too
  { said: "Kids are up. Something we can all watch.", company: "kids" },
  { said: "Nothing scary. She's four.", company: "kids" },
  { said: "Rainy afternoon with the kids.", company: "kids" },
  { said: "A sleepover and eight children.", company: "kids" },
  { said: "A six-year-old's choice, but I have to sit through it too.", company: "kids" },
  { said: "Something that'll get them off the tablet.", company: "kids" },
  { said: "Something with animals for the little one.", company: "kids" },
  { said: "An anime film the children can watch with us.", company: "kids" },
  { said: "A Ghibli film for my daughter's first movie night.", company: "kids" },
  { said: "My son wants dinosaurs. Nothing that gives him nightmares.", company: "kids" },
  { said: "A funny film for a seven-year-old and a very tired parent.", company: "kids" },
  { said: "Something with songs the kids can shout along to.", company: "kids" },
  { said: "A nature documentary the children will actually watch.", company: "kids" },
  { said: "Bedtime soon. Something calm for the kids.", company: "kids" },
  { said: "The cousins are here, ages five to twelve.", company: "kids" },
  // nobody in particular
  { said: "Good mood, got the whole evening.", company: null },
  { said: "Restless. I can't sit still for anything slow.", company: null },
  { said: "Nostalgic for being a kid. Something from the nineties.", company: null },
  { said: "Raining all weekend. Not going out.", company: null },
  { said: "I've got two hours and no plans.", company: null },
  { said: "I need to feel better about people.", company: null },
  { said: "Everything went wrong today. Something kind.", company: null },
  { said: "Bored of everything I usually watch. Something Korean, then.", company: null },
  { said: "Sunday afternoon, nothing to do.", company: null },
  { said: "I want to be impressed.", company: null },
  { said: "Make me laugh. Nothing has in a week.", company: null },
  { said: "Something I'll still be thinking about tomorrow.", company: null },
  { said: "Surprise me.", company: null },
  { said: "The best-rated thing in the box.", company: null },
  { said: "The highest rated thing here.", company: null },
  { said: "The newest thing you've got.", company: null },
  { said: "The oldest thing you've got that's still good.", company: null },
  { said: "Something short and very good.", company: null },
  { said: "Under two hours, and worth every minute.", company: null },
  { said: "A trilogy. I've got all day.", company: null },
  { said: "One episode, then bed. Honestly.", company: null },
  { said: "Something with one season only. No commitment.", company: null },
  { said: "Short episodes, I keep getting interrupted.", company: null },
  { said: "A miniseries I can finish this weekend.", company: null },
  { said: "Something Thai.", company: null },
  { said: "A GDH film, the ones that make you cry.", company: null },
  { said: "Thai horror, the kind that actually scares Thai people.", company: null },
  { said: "A Thai series everyone was talking about.", company: null },
  { said: "Something Korean.", company: null },
  { said: "K-drama, the sort people binge.", company: null },
  { said: "A Korean film with a twist I won't see coming.", company: null },
  { said: "Japanese, something old.", company: null },
  { said: "A Kurosawa film.", company: null },
  { said: "Studio Ghibli.", company: null },
  { said: "Anime, and make it good.", company: null },
  { said: "Anime, but not a long series.", company: null },
  { said: "A sports anime to get me off the sofa.", company: null },
  { said: "Something Chinese I'd have heard of.", company: null },
  { said: "Something from Hong Kong, with fighting in it.", company: null },
  { said: "Wuxia. Swords and flying.", company: null },
  { said: "A Stephen Chow comedy.", company: null },
  { said: "A Wong Kar-wai film.", company: null },
  { said: "A Taiwanese drama, the slow kind.", company: null },
  { said: "Bollywood, three hours, I don't mind.", company: null },
  { said: "French, and I'll read the subtitles.", company: null },
  { said: "Italian, something classic.", company: null },
  { said: "Scandinavian and cold.", company: null },
  { said: "British, and very British.", company: null },
  { said: "A Spanish-language film.", company: null },
  { said: "A Turkish series, the ones that go on forever.", company: null },
  { said: "Something from the seventies.", company: null },
  { said: "Something from the eighties.", company: null },
  { said: "Something from the nineties.", company: null },
  { said: "Something from the 2020s.", company: null },
  { said: "A black-and-white classic from the forties or fifties.", company: null },
  { said: "Silent era, if there's anything good.", company: null },
  { said: "A comedy from before I was born.", company: null },
  { said: "A classic from the fifties that still holds up.", company: null },
  { said: "A Netflix original that was actually good.", company: null },
  { said: "A documentary about a crime.", company: null },
  { said: "A nature documentary, something calming.", company: null },
  { said: "A documentary about food.", company: null },
  { said: "A documentary about someone very good at one thing.", company: null },
  { said: "A reality show I won't feel bad about.", company: null },
  { said: "A cooking competition.", company: null },
  { said: "A horror film that's actually frightening.", company: null },
  { said: "A psychological thriller.", company: null },
  { said: "A thriller that doesn't let up.", company: null },
  { said: "Spies, and nobody can be trusted.", company: null },
  { said: "A heist. Clever people stealing things.", company: null },
  { said: "A con artist running a long game.", company: null },
  { said: "A gangster film.", company: null },
  { said: "A film noir.", company: null },
  { said: "Somebody getting revenge.", company: null },
  { said: "A courtroom drama. People arguing well.", company: null },
  { said: "A detective who is worse at life than at the job.", company: null },
  { said: "A western.", company: null },
  { said: "A war film, from the ground.", company: null },
  { said: "Science fiction, the thoughtful kind.", company: null },
  { said: "Space, and make it quiet.", company: null },
  { said: "Something like Interstellar, but shorter.", company: null },
  { said: "Fantasy, with a proper world in it.", company: null },
  { said: "A monster movie, an honest one.", company: null },
  { said: "Superheroes, and make it fun.", company: null },
  { said: "A musical.", company: null },
  { said: "Something about music.", company: null },
  { said: "A dark comedy.", company: null },
  { said: "Animation, but for adults.", company: null },
  { said: "A coming-of-age film.", company: null },
  { said: "A film about a friendship.", company: null },
  { said: "A film about grief that isn't unbearable.", company: null },
  { said: "A romance that isn't sentimental.", company: null },
  { said: "A road trip.", company: null },
  { said: "A survival story.", company: null },
  { said: "A biopic of someone interesting.", company: null },
  { said: "A true story that actually happened.", company: null },
  { said: "Something historical, and roughly accurate.", company: null },
  { said: "Someone building something impossible.", company: null },
  { said: "Someone pretending to be someone else.", company: null },
  { said: "A film set entirely in one room.", company: null },
  { said: "Something with a twist I won't see coming.", company: null },
  { said: "Something with Tom Hanks.", company: null },
  { said: "A Hitchcock film.", company: null },
  { said: "Anything with Toshiro Mifune.", company: null },
  { said: "Batman.", company: null },
  { said: "Something about a family falling apart.", company: null },
  { said: "Politics, and people who are good at it.", company: null },
  { said: "Journalism, and someone telling the truth anyway.", company: null },
  { said: "Boxing, or anything with training in it.", company: null },
  { said: "Chess, cards, anything with a game in it.", company: null },
  { said: "Something I can fall asleep to.", company: null },
];

export type Deck = { readonly shown: Suggestion | null; readonly left: readonly Suggestion[] };
export const EMPTY_DECK: Deck = { shown: null, left: [] };

/** Fisher-Yates; `random` is a parameter so a test can deal the same deck twice. */
export const shuffled = <T,>(items: readonly T[], random: () => number = Math.random): readonly T[] => {
  const out = [...items];
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
};

/** A fresh shuffle, cut so the first card up is never the one still on the table. */
const deal = (items: readonly Suggestion[], shown: Suggestion | null, random: () => number) => {
  const cards = shuffled(items, random);
  return cards.length > 1 && cards[0].said === shown?.said ? [...cards.slice(1), cards[0]] : cards;
};

/** Turns the next card. Every card comes up once before any comes up again; a spent deck is dealt afresh. */
export const draw = (deck: Deck, items: readonly Suggestion[], random: () => number = Math.random): Deck => {
  const [card, ...left] = deck.left.length > 0 ? deck.left : deal(items, deck.shown, random);
  return { shown: card ?? null, left };
};
